FROM nvidia/cuda:12.1.0-cudnn8-devel-ubuntu22.04

RUN apt update -y && apt upgrade -y && apt install -y --no-install-recommends  \
    git \
    git-lfs \
    python3 \
    python3-pip \
    python3-dev \
    wget \
    curl \
    vim \
	gcc \
	g++ \
&& rm -rf /var/lib/apt/lists/*

# ln python3
RUN ln -s $(which pip3) /usr/local/bin/pip && ln -s $(which python3) /usr/local/bin/python

# torch
RUN pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121 --no-cache

# transformers 
RUN pip install git+https://github.com/huggingface/transformers

# vLLM 
RUN pip install vLLM

# fschat pydantic 
RUN pip install "fschat[model_worker]"==0.2.36 --no-cache

# gptq
RUN pip install --no-cache "optimum==1.17.1" "auto-gptq==0.7.1" 

# autoawq
RUN pip install --no-cache autoawq 


#fix pydantic
#RUN pip uninstall pydantic -y 
#RUN pip install pydantic==1.10.11 --no-cache