ARG from=nvidia/cuda:11.7.1-cudnn8-runtime-ubuntu22.04

FROM ${from} as base


RUN apt update -y && apt upgrade -y && apt install -y --no-install-recommends  \
    git \
    git-lfs \
    python3 \
    python3-pip \
    python3-dev \
    wget \
    curl \
    vim \
	gcc \
	g++ \
&& rm -rf /var/lib/apt/lists/*

# torch
RUN pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu117 --no-cache

# transformers 
RUN pip3 install git+https://github.com/huggingface/transformers

# vLLM RUN pip3 install vLLM>=0.3.0 
# Build from source
RUN git clone https://github.com/vllm-project/vllm.git /vllm && cd vllm && pip install -e . 

# fschat pydantic 
RUN pip3 install "fschat[model_worker]"==0.2.36 --no-cache

# gptq
RUN pip3 install --no-cache "optimum==1.17.1" "auto-gptq==0.7.1" 

# autoawq
RUN pip3 install --no-cache autoawq 


#fix pydantic
RUN pip3 uninstall pydantic -y 
RUN pip3 install pydantic==1.10.11 --no-cache

