services:
  Qwen2-VL:
    build:
      args:
        http_proxy: http://192.168.31.98:1080
        https_proxy: http://192.168.31.98:1080
      context: ./
      dockerfile: Dockerfile
    image: lianshufeng/llm:Qwen2-VL
    container_name: Qwen2-VL
    volumes:
      - ./models:/models
#      - ./src:/opt/app
    restart: always
    ports:
      - "8000:8000"
    environment:
      - CUDA_VISIBLE_DEVICES=1 # 多卡 0,1
    command: python server.py
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: "all"
              capabilities: [gpu]
