services:
  deepface:
    image: lianshufeng/llm:deepface
    container_name: deepface
    volumes:
      - ./weights:/root/.deepface/weights
      - ./dataset:/app/dataset
    restart: always
    ports:
      - "5000:5000"
    environment:
      - ELASTIC_PASSWORD=es7896@2025
      - ELASTICSEARCH_HOSTS=http://127.0.0.1:9200
      - CUDA_VISIBLE_DEVICES=0,1 # 多卡 0,1
#    working_dir: /opt/src
#    command: python app.py --device=cuda #cpu
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: "all"
              capabilities: [gpu]
