services:
  deepface:
#    image: serengil/deepface
#     image: tensorflow/tensorflow:2.11.0-gpu
    image: lianshufeng/llm:deepface
    container_name: deepface
    volumes:
      - ./weights:/root/.deepface/weights
      - ./dataset:/app/dataset
    restart: always
    ports:
      - "5000:5000"
    environment:
      - CUDA_VISIBLE_DEVICES=0,1 # 多卡 0,1
#    working_dir: /opt/src
#    command: python app.py --device=cuda #cpu
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: "all"
              capabilities: [gpu]
