services:
  localai:
    # image: localai/localai:latest-aio-gpu-nvidia-cuda-12
    image: localai/localai:latest-gpu-nvidia-cuda-12
    ports:
      - "8080:8080"
    environment:
      - DEBUG=true
      - CUDA_VISIBLE_DEVICES=0,1 # 多卡 0,1
      - http_proxy=http://192.168.31.98:1080
      - https_proxy=http://192.168.31.98:1080
    volumes:
      - ./models:/build/models:cached
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: "all"
              capabilities: [gpu]