version: "3"

services:

  qwen1.5-cpu:
    build:
      # args:
        # http_proxy: http://192.168.31.98:1080
        # https_proxy: http://192.168.31.98:1080
      context: ./
      dockerfile: Dockerfile-cpu
    image: lianshufeng/qwen:1.5-cpu
    ports:
      - "8000:8000"
    privileged: true
    container_name: qwen1.5-cpu
    restart: always
    volumes:
      - ../Qwen1.5-0.5B-Chat:/models
    command: python3 -m vllm.entrypoints.openai.api_server --served-model-name Qwen1.5-0.5B-Chat --model /models