ARG from=ubuntu:22.04

FROM ${from} as base


RUN apt update -y && apt upgrade -y && apt install -y --no-install-recommends  \
    git \
    git-lfs \
    python3 \
    python3-pip \
    python3-dev \
    wget \
    curl \
    vim \
&& rm -rf /var/lib/apt/lists/*

# torch
RUN pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu --no-cache

# transformers 
RUN pip3 install transformers>=4.37.0 --no-cache


# fastchat cpu
RUN pip3 install "fschat[model_worker]"==0.2.36 --no-cache
RUN pip uninstall pydantic -y #fix pydantic
RUN pip install pydantic==1.10.11 --no-cache

# script
ADD ./fastchat.sh /fastchat.sh
