name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image in vllm directory
        working-directory: vllm
        run: |
          docker build -f Dockerfile-cuda12.1 -t vllm-cuda121:$(date +%s) .
